services:
  docassemble:
    build:
      dockerfile: slimcontainer/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: docassemble
      POSTGRES_DB: docassemble
