# to not assume that there's a custom python install under /usr/share/docassemble/local3.10
packages: /usr/local
# to avoid exiting with "Unable to modify the timestamp of the WSGI file"
allow restarting: False
# to avoid having initialize trying to create /var/www/.pypirc, instead writing to config dir
pypirc path: /usr/share/docassemble/config/.pypirc

debug: True
enable playground: True
allow demo: True
exitpage: https://docassemble.org
db:
  prefix: postgresql+psycopg2://
  name: docassemble
  user: docassemble
  password: abc123
  host: postgres
  port: null
  table prefix: null
  backup: true
oauth:
  facebook:
    enable: False
  google:
    enable: False
  auth0:
    enable: False
  keycloak:
    enable: False
  twitter:
    enable: False
  azure:
    enable: False
  github:
    enable: False
secretkey: eGJarOFpVxQSqxdoSqhGHYadBriVeOVf
backup days: 0
default title: docassemble
default short title: doc
mail:
  username: null
  password: null
  server: localhost
  default sender: '"Administrator" <no-reply@example.com>'
server administrator email: webmaster@localhost
default interview: docassemble.base:data/questions/default-interview.yml
language: sv
locale: sv_SE.utf8
os locale: sv_SE.UTF-8 UTF-8
timezone: Europe/Stockholm
redis: redis://redis
rabbitmq: pyamqp://guest@rabbitmqserver.local//
celery processes: null
collect statistics: false
kubernetes: false
ec2: false
log server: null
use cloud urls: false
use minio: false
use https: false
use lets encrypt: false
lets encrypt email: null
behind https load balancer: false
xsendfile: true
update on start: initial
allow updates: true
url root: http://da
external hostname: none
expose websockets: false
websockets ip: null
websockets port: null
# right now the uwsgi server and docassemble does not play nice with regards to
# where the app should actually be mounted... need to dig further in how the
# standard docassemble container uses wsgi to mount it at a path
# root: /da/
root: /
words:
  - docassemble.base:data/sources/us-words.yml
  - docassemble.base:data/sources/sv-words.yml
allow non-idempotent questions: False
restrict input variables: True
web server: nginx
new markdown to docx: True
stable version: false
sql ping: false
default icons: font awesome
config from: null
enable unoconv: false
checkin interval: 2000